name: $MY_PYTHON_VIRTURL_ENV_NAME  # 1. ç’°å¢ƒåç¨±ï¼Œè©²åç¨±å¿…é ˆèˆ‡install.batã€uninstall.batç›¸åŒ

channels:
  - conda-forge        # 2. å¥—ä»¶ä¾†æºé »é“
  - defaults
#-------------------------------------------------------------------------------
# ğŸ“’å¥—ä»¶å®‰è£èªªæ˜ï¼š
# 1. æœå°‹å®‰è£å¥—ä»¶ç›¸é—œè³‡è¨Šï¼š 
#   a.ã€ https://conda-forge.org/packages/ ã€‘
#   b.ã€ conda repoquery search -c conda-forge TA-Lib ã€‘
#   è©²æœå°‹çµæœå¯çœ‹å‡ºæœ‰å“ªäº›ç‰ˆæœ¬èˆ‡æ”¯æ´pythonçš„ç‰ˆæœ¬ã€‚
#    -c é€šé“é¸æ“‡ conda-frogeã€default
# 2. å¦‚æœcondaç„¡æ³•æœå°‹åˆ°å°±è¦åˆ°PyPiå®˜ç¶²æœå°‹ã€”https://pypi.org/ã€•
#
dependencies:
  # - python=3.10.8      # 3. æ ¸å¿ƒå¥—ä»¶ (ä¾‹å¦‚ï¼šPython ç‰ˆæœ¬)ï¼ŒæŒ‡å®šç‰ˆæœ¬ä½¿ç”¨ = ä¸”ä¸è¦æœ‰ç©ºç™½
  # å› ç‚ºPythonåŸ·è¡Œæ•ˆç‡æ”¹å–„ä¸”Shioajiä¹Ÿæ”¯æ´3.11æ‰€ä»¥ç½®æ›æˆè©²ç‰ˆæœ¬ã€‚
  # ã€https://www.vnpy.com/forum/topic/34035-veighnafa-bu-v4-1-0-zheng-ti-wan-cheng-mo-kuai-yi-zhi-gong-zuoã€‘
  - python=3.11.13       
  - pip
  # - TA-Lib>=0.6.4
  - pip:               # 4. Pip å¥—ä»¶ï¼ŒæŒ‡å®šç‰ˆæœ¬ä½¿ç”¨ == ä¸”ä¸è¦æœ‰ç©ºç™½
    - python-dotenv>=1.1.1    # for ç’°å¢ƒè®Šæ•¸
    - pydantic==2.11.5        # shioaji 1.2.7 è¦æ±‚çš„ä½†æ˜¯FastAPIä¹Ÿéœ€æ±‚è©²å¥—ä»¶--------    
    # - -r file:requirements.txt
    # - requests
    # - beautifulsoup4

#-------------------------------------------------------------------------------
#
# è¨­ç½®ç’°å¢ƒè®Šæ•¸
#
# variables:
#   MY_VAR: something
#   OTHER_VAR: ohhhhya